AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Place du village
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  LambdaRoleName:
    Type: String
  Stage:
    Type: String
  S3MessagesBucket:
    Type: String
  WhatsappGroupId:
    Type: String
  OpenAiApiKey:
    Type: String

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 256
    Timeout: 30
    Architectures:
    - x86_64
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        STAGE: !Ref Stage
        S3_MESSAGES_BUCKET: !Ref S3MessagesBucket
        WHATSAPP_GROUP_ID: !Ref WhatsappGroupId
        OPENAI_API_KEY: !Ref OpenAiApiKey

  Api:
    TracingEnabled: true

Resources:
  SendDaily:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      CodeUri: .
      Handler: src/handlers/sendDaily.handler
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/${LambdaRoleName}"
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Enabled: true
            Schedule: cron(0 9 * * ? *)
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2022"
        Sourcemap: true
        EntryPoints:
        - src/handlers/sendDaily.ts
        External:
        - fluent-ffmpeg

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true
